# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'END-Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for END-Test
#  pod 'Alamofire', '~> 4.7'
  pod 'Hero'

#  target 'END-TestTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
